import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import ThemeProvider from '@/components/ThemeProvider'
import Provider from '@/components/QueryProvider'
import dynamic from "next/dynamic";

const ThemeToggle = dynamic(() => import('@/components/ThemeToggle'), { ssr: false })

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by crud next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
      >
        <Provider>
          <div className='flex flex-col w-full h-[100vh]'>
              <div className='w-full h-[60px] flex'>
                  <div className='justify-self-end'>
                      <ThemeToggle/>
                  </div>
              </div>
              <div className='flex-grow min-h-0'>
                  {children}
              </div>
          </div>
        </Provider>
      </ThemeProvider>
      </body>
    </html>
  );
}
